name: lightfootcat
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - pip
  - conda
  - accelerate
  - pandas
  - jupyterlab
  - pillow
  - tesserocr
  - matplotlib
  - opencv
  - transformers
  - json-repair
  - poppler
  - pip:
    - pdf2image
    - natsort
