channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pip<24.1
  - conda
  - accelerate
  - pandas
  - jupyterlab
  - pillow
  - tesserocr
  - matplotlib
  - opencv
  - transformers
  - json-repair
  - poppler
  - pydantic
  - pytesseract
  - spacy
  - numpy
  - thinc
  - cupy
  - pip:
    - pdf2image
    - natsort
    - pygbif
    - taxonerd
    
