name: lightfootcat
channels:
  - bioconda
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python==3.11.11
  - pip
  - pytorch
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - jupyterlab
  - pillow
  - tesserocr
  - matplotlib
  - opencv
  - transformers
  - yaml
