#Define variable configuration
# Model config
model: "qwen2.5"
output_save_file_name: "lightfootcat"
max_tokens: 4096
max_chunk_size: 3000
output_save_path: "outputs/lightfootcat_with_extract/"    # Where to save the output
batch_size: 
ocr_model: "mistral7b"
ocr_extraction_model: null
ocr_temperature: 0.1
transcription_temperature: 0.1
timeout: 4 # Number of tries
# Data reader config
crop: True
padding: 100.0
resize_factor: 0.4
remove_area_perc: 0.01
middle_margin_perc: 0.20
has_columns: True
grayscale_only: False
double_pages: True
# define to inherit any missing prompts from the default prompt
inherit_default: False
# Path to default file if inheriting from another custom prompt
default_file: None
# Any divisions in the catalogue
divisions: ["Dicotyledones", "Monocotyledones", "Pteridophyta", "Hepaticae", "Algae"]
# System defines the system prompt to the model
system:
  # Setup defines the model setup prompt. This lets the model know what area of knowledge to focus on for this task
  setup: >
    You are a system that converts botanical text into strictly valid JSON.
  # context defines the context of the task. This includes the input to the model and the description of said input
  # instructions define the step-by-step instructions for the model to follow through
  instructions: |
    Reformat the following botanical text **exactly** into JSON according to the provided schema.

    **Strict Output Rules:**
    - The output must be a single **valid JSON object** with no surrounding text, explanations, markdown, or formatting.
    - **Do not generate any extra text** beyond the required JSON structure.
    - **All keys must be quoted properly**.
    - **No trailing commas** should be present.
    - Extract data **as-is** from the input text; do not modify, paraphrase, or infer missing details.
    - Make sure all quotation marks, backslashes, and special characters inside description fields are properly escaped according to JSON standards. Double quotes inside content must be escaped as \".
    - When extracting text like dates, locations, or scientific references, maintain the exact format from the source without attempting to standardize or reformat.
    Output must match the schema structure and follow rules
  # rules define the key-value rules for each expected key in the output json dict
  # rules:
  #   familyName: >
  #     The scientific family name in uppercase. If not available, use "N/A".
  #   species: >
  #     A list of dictionaries for each species under the family. Each dictionary should include:
  #     - speciesName: The full scientific name as written in the text.
  #     - folders: A list of dictionaries, each containing:
  #          - description: A description of the folder contents.For description fields that contain citations or quotes, ensure proper escaping of all contained quotation marks.

  # schema defines the output json structure
  schema: default

  examples: 
    - input_species_and_records: |
        ACERACEAE

        Acer campestre L.

        1 folder. Acer campestre [TA]

        Acer pseudoplatanus L.
        
        2 folders.
        
        Folder

    - output_species_and_records: |
        {"familyName": "ACERACEAE", 
        "species": [{"speciesName": "Acer campestre L\.",
              "folders": [{"description": "Acer campestre \[TA\]"}]},
            {"speciesName": "Acer pseudoplatanus L\."
              folders :[{"description": "Folder"}]}]}

    - input_species_only: |
        ACERACEAE

        1. Acer Pseudo-Platanus [G]. i. "Maple. Bulls: [Bulstrode] Park" [JL]
        
        Folder 

    - output_species_only: |

        {"familyName": "ACERACEAE", 
        "species": [{"speciesName": "N\A",
              "folders": [{"description": "1\. Acer Pseudo\-Platanus \[G\]\. i\. \"Maple\. Bulls\: \[Bulstrode\] Park\" \[JL\]"}, {"description": "Folder"}]},]}

    - input_records_only: |
        EMNACEAE

        Lemna trisulca L.

    - output_records_only: |   

        {"familyName": "EMNACEAE", 
        "species": [{"speciesName": "Lemna trisulca L\.", "folders": [{"description": "N\A"}]},]} 

# user defines the user input. This can contain more than one prompt. 
# Different prompts will be passed to the model as individual inputs
user:
  # the prompt defines the user's prompt to the model
  text: | 
   Reformat the text below exactly into JSON according to the schema provided.
    Only output the JSON object and nothing else.
  
   Extracted text:
   {extracted_text} 
    
